# Generated by Django 4.2.5 on 2023-10-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0004_alter_petshop_options_alter_reserva_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_apenas',
            field=models.DateField(blank=True, help_text='dd/mm/aaaa', null=True, verbose_name='Data'),
        ),
    ]
