# Generated by Django 4.2.5 on 2023-10-03 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0005_reserva_data_apenas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='data',
        ),
    ]
